name: Test Automation Workflow

on:
  schedule:
    - cron: 30 03 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install Maven Dependencies
        run: mvn dependency:resolve

      - name: Compile the Project
        run: mvn compile

      - name: Run Tests
        run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Test Logs
          path: log/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Test Reports
          path: report.html

      - name: Test Execution Status
        run: echo "Test Execution Completed"
