# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Automation WorkFlow

on:
  schedule:
  - cron: 30 03 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install -y <required_package>
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser -DisLambdaTest=true -DisHeadless=false

    - name: Upload a Test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test logs
        path: log/
 
    - name: Upload a Test Reports
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Reports
        path: report.html

      
    - name: Test Execution Status
      run: echo "Test Execution Completed"
